// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9JjVrFsGSjij7OksITSW4a3rYNLlGk80',
    appId: '1:757968596460:web:96b6c2d95de91574c764c9',
    messagingSenderId: '757968596460',
    projectId: 'splitshare-48457',
    authDomain: 'splitshare-48457.firebaseapp.com',
    storageBucket: 'splitshare-48457.appspot.com',
    measurementId: 'G-LSLFH6BYNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgmZ-DVVVGcQs8GMijSyozL3bdsbOgmm8',
    appId: '1:757968596460:android:6789883f7ae2d96cc764c9',
    messagingSenderId: '757968596460',
    projectId: 'splitshare-48457',
    storageBucket: 'splitshare-48457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHXAN1d4c0j_zgD_a9ouM8Wa2p_aEY44',
    appId: '1:757968596460:ios:c8bcf6723619bc02c764c9',
    messagingSenderId: '757968596460',
    projectId: 'splitshare-48457',
    storageBucket: 'splitshare-48457.appspot.com',
    iosBundleId: 'com.splitshare.splitshare',
  );
}
